<?php
return array(
	'URL_ROUTER_ON'   => true,
    'URL_ROUTE_RULES'=>array(
        'index' => 'Home/Index/index',
        'login' => 'Home/Users/login',
        'register' => 'Home/Users/register',
        'pass' => 'Home/Users/lostpassword',
        'z/:drivesId\d'    => 'Home/Drives/diverDetail',
        'v/:visaId\d' => 'Home/Visas/index',
        'm/:goodsId\d' => 'Home/Goods/index',
        'a/:catId\d' => 'Home/Articles/getContent',
        'u' => 'Home/Users/user',
        'doReName' => 'Home/Users/doReName',
        'userset' => 'Home/Users/userset',
        'o/:orderId\d' => 'Home/Orders/orderConfirm',
        'p/:orderId\d' => 'Home/Pay/index',
        'wx/:orderId/:values' => 'Home/Pay/goPay',
        'yl/:orderId/:values' => 'Home/Pay/goPay',
        'zfb/:orderId/:values' => 'Home/Pay/goPay',
        'order' => 'Home/Orders/order',
        'wxBack/:orderId' => 'Home/Pay/wxSuBack',
        'wxErBack/:orderId' => 'Home/Pay/wxErBack',
        'info/:orderId' => 'Home/Orders/orderInfo',
        'car/:orderId' => 'Home/Orders/orderCar',
        'comment/:orderId' => 'Home/Orders/ordersComment',
    ),
);